open_shade:
  name: Open Shade
  description: Opens the shade to 100% open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

close_shade:
  name: Close Shade
  description: Closes the shade to 100% closed
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

stop_shade:
  name: Stop Shade
  description: Stops the shade at the current position
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

set_shade_position:
  name: Set Position
  description: Sets the position to percentage of open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    position:
      name: Position
      description: The position of the shade
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

tilt_open:
  name: Tilt Open
  description: Tilts the slats open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

tilt_close:
  name: Tilt Close
  description: Tilts the slats closed
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

set_tilt_position:
  name: Set Tilt Position
  description: Sets the tilt position to percentage of open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    tilt_position:
      name: Position
      description: Tilt position of the slats
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_current_position:
  name: Change Position
  description: Sets the current position without moving the motor
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    position:
      name: Position
      description: The position to be set
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_current_tilt_position:
  name: Change Tilt Position
  description: Sets the current tilt position without moving the motor
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    tilt_position:
      name: Position
      description: The tilt position to be set
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_sunny:
  name: Set Sunny
  description: Sends the sensor commands to the motor indicating whether it is sunny or not
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    sunny:
      name: Is Sunny
      description: A boolean indicating whether it is sunny or not
      required: true
      selector:
        boolean:

set_windy:
  name: Set Windy
  description: Sends the sensor commands to the motor indicating whether it is windy or not
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    windy:
      name: Is Windy
      description: A boolean indicating whether it is windy or not
      required: true
      selector:
        boolean:

send_command:
  name: Send command
  description: Send any command from RTS protocol
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    command:
      name: Command
      description: Command to send
      required: true
      example: prog
      selector:
        select:
          options:
              - "Up"
              - "My"
              - "Down"
              - "Toggle"
              - "Prog"
              - "UpDown"
              - "MyUp"
              - "MyDown"
              - "MyUpDown"
              - "StepUp"
              - "StepDown"
              - "Flag"
              - "SunFlag"
              - "Favorite"
              - "Stop"
          mode: dropdown
    repeat:
      required: true
      name: Repeat
      description: Number of time the command will be sent
      selector:
        number:
          min: 1
          max: 50
      default: 1
send_step_command:
  name: Send Step command
  description: Send a step command with a step size
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    direction:
      required: true
      name: Direction
      description: The direction that the motor will step
      selector:
        select:
          options:
            - "Up"
            - "Down"
    step_size:
      required: true
      name: Step Size
      description: The size of the step with 127 being the largest step
      selector:
        number:
          min: 1
          max: 127

reboot:
  name: Reboot
  description: Reboot the ESPSomfy Device
  target:
    entity:
      integration: espsomfy_rts
      domain: button
      supported_features:
        - fan.FanEntityFeature.SET_SPEED

backup:
  name: Backup
  description: Backup the ESPSomfy Device
  target:
    entity:
      integration: espsomfy_rts
      domain: button
      supported_features:
        - fan.FanEntityFeature.OSCILLATE



