open_shade:
  name: Open Shade
  description: Opens the shade to 100% open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

close_shade:
  name: Close Shade
  description: Closes the shade to 100% closed
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

stop_shade:
  name: Stop Shade
  description: Stops the shade at the current position
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

set_shade_position:
  name: Set Position
  description: Sets the position to percentage of open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    position:
      name: Position
      description: The position of the shade
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

tilt_open:
  name: Tilt Open
  description: Tilts the slats open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

tilt_close:
  name: Tilt Close
  description: Tilts the slats closed
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

set_tilt_position:
  name: Set Tilt Position
  description: Sets the tilt position to percentage of open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover
  fields:
    tilt_position:
      name: Position
      description: Tilt position of the slats
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"





